version: '1.0'

services:
  cmsapi:
    container_name: cms-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 8082:80

networks:
  default:
      name: srvnecmettin